### ISSUE TITLE
feat: restructure architecture (part 2)

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#412]
**Tasks -**
- [x] add support to generate service token for analytics server **[GUI update required**] #420
- [x] allow to create user from setup page [only for first time]   #419 [**GUI update required**]
- [x] git branch list api #418 [**GUI update required**]
- [x] fix #369
- [x] #421
- [x] #422 **[Docs update required]**
- [x] for local registry run a **image registry** instead of dumping locally #417
- [x] https://github.com/swiftwave-org/swiftwave/pull/424
- [x] server and cluster setup from GUI  [**GUI update required**]
