### ISSUE TITLE
feat: platform future scopes and goals

### ISSUE THREAD

**Issue by tanmoysrt** [swiftwave-org/swiftwave#53]
###  Future Scopes and Goals
- [x] Move docker files to debian based images #56
- [x] #101 and #102
- [x] #107
- [x] #116 
- [x] #128
- [x] #117 
- [x] #118 
- [x] #136
- [x] #135
- [x] #119 
- [x] #120
- [x] #121
- [x] #122
- [x] #123
- [x] #57
- [x] #130
- [x] #186
- [x] #187
- [x] #202
- [x] #212
- [x] #221
- [x] #152
  - CLI
  - REST API
  - Grqphql Endpoint
- [x] #251
- [x] Renew Service Endpoint TLS certificates automatically before 30 days
- [x] #423
- [x] #243 
- [x] #201
- [x] #297
- [x] #148
- [x] #219
- [x] Provide option to expose more ports except 80, 443 for haproxy service
- [x] Use app ID instead of app name for haproxy configuration
- [x] #163
- [x] ~Support for `Production` and `Development` docker templates~
   - ~Because the Production docker template required to install additional OS packages due to minified images~
   - *Don't required, as user can bring own docker file + edit on the web*
   - *For frontend, we will keep production grade dockerfiles as well* 
- [x] #105
- [x] live logging of runtime and build logs #90
- [x] Support multiple replica support of applications to scale #107
- [x] Multi-cluster deployment support
  - [x] Multi cluster deployment docker swarm support
    - [x] Postgres
    - [x] RabbitMQ + Redis on cluster
    - [x] Local Task Queue + Cache 
  - [x] #200
- [x] #144
- [x] #150
- [x] #259
- [x] #203
- [x] ~Convenient Solution for Installer and a Release System to provide updates to swiftwave services~ _No longer required_
- [x] #255
- [x] #308
- [x] #412 #308

**Comment by tanmoysrt** [comment]
After 5 months, all the required tasks completed :partying_face: 
Long way to go btw, hope to have a stable and complete version at the end of year 2024
